# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Vctl < Formula
  desc "Vault-backed infrastructure access CLI"
  homepage "https://github.com/ghdwlsgur/vctl"
  version "0.2.14"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ghdwlsgur/vctl/releases/download/v0.2.14/vctl_0.2.14_darwin_amd64.tar.gz"
      sha256 "7df9c33134909485e0c10721328c8a91eecf72fb640a27e1d0335661415edbf3"

      define_method(:install) do
        bin.install "vctl"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ghdwlsgur/vctl/releases/download/v0.2.14/vctl_0.2.14_darwin_arm64.tar.gz"
      sha256 "d1a900377bae506f0cc056b9e8e1604431e7aa98ff2825f8e04ab2bcf66c0d00"

      define_method(:install) do
        bin.install "vctl"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/ghdwlsgur/vctl/releases/download/v0.2.14/vctl_0.2.14_linux_amd64.tar.gz"
      sha256 "79dcbe8a64afe9d6c3f5841b123cdeb58f43aeeeb8ca053c1d75040d764bf69c"
      define_method(:install) do
        bin.install "vctl"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ghdwlsgur/vctl/releases/download/v0.2.14/vctl_0.2.14_linux_arm64.tar.gz"
      sha256 "79f83f3dde0caaeb417e7a607ebb8903ad1aa82dc419f5388b122e6b8bb209eb"
      define_method(:install) do
        bin.install "vctl"
      end
    end
  end

  test do
    system "#{bin}/vctl", "--version"
  end
end
